### ISSUE TITLE
Fix Travis configuration

### ISSUE THREAD

**Issue by hugobessa** [hugobessa/django-shared-schema-tenants#36]
Due to some misconfiguration, Travis build is broken. Any new code will break on the CI. I'll probably have some time to investigate this after July.

**Comment by techdragon** [comment]
#38 fixed the issue in my testing. Waiting for the travis-ci build on the pull request to complete to be sure 👍  Seems to have stalled on one of the builds. I'll do a minor edit and push a rebuild to confirm it definitely works.

**Comment by techdragon** [comment]
@hugobessa The stall was definitely something on Travis-CI's end. I've pushed an update with just a whitespace change to my branch to trigger a re-build of #38 and now it passes. Should be good to go ahead and merge #38 and close this one. 👍
